name: CI

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

permissions:
  contents: read

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          pyproject.toml
          requirements*.txt
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Run ruff linting
      run: |
        ruff check src tests
        ruff format --check src tests
    
    - name: Run mypy type checking
      run: |
        mypy src/cad_datamodel --strict
    
    - name: Run tests with coverage
      run: |
        pytest tests/unit -v --cov=src/cad_datamodel --cov-report=term-missing --cov-report=xml --cov-report=html
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-${{ matrix.python-version }}
        path: |
          coverage.xml
          htmlcov/
      if: matrix.python-version == '3.12'  # Only upload for latest Python
    
    - name: Build package
      run: |
        pip install build
        python -m build
    
    - name: Verify package installation
      run: |
        # Create a fresh virtual environment
        python -m venv test_env
        source test_env/bin/activate
        pip install dist/*.whl
        python -c "import cad_datamodel; print(f'Successfully imported {cad_datamodel.__name__} version {cad_datamodel.__version__}')"
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ matrix.python-version }}
        path: dist/
      if: matrix.python-version == '3.12'  # Only upload for latest Python

  # Separate job to verify all tests passed
  verify:
    name: Verify CI Success
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: CI Success
      run: echo "All CI checks passed successfully!"